### ISSUE TITLE
Do we need an "issue template"

### ISSUE THREAD

**Issue by sm4rk0** [cmprescott/ansible-xml#124]
...that would direct issue reporters to ansible/ansible?
https://help.github.com/articles/creating-an-issue-template-for-your-repository/

Or [disabling issues](https://help.github.com/articles/disabling-issues/) at all?

**Comment by ksylvan** [comment]
Yes. Sounds like a good idea.

**Comment by dagwieers** [comment]
@sm4rk0 This was already discussed with @cmprescott , but since I didn't have your email-address I couldn't put you in cc:. We should have both issue and PR templates stating that the module is upstream and no issues/PRs are being accepted through this project.

We should also update the README in this project, as well as make it clear from the repository title/description.

I wouldn't disable issues, as that makes the existing issues unavailable (and those happento be still very useful for people using xml).

**Comment by sm4rk0** [comment]
@dagwieers I've sent you an email.
I didn't know the existing issues would be completely unavailable if disabled.
[issue_template.md](https://github.com/cmprescott/ansible-xml/blob/master/.github/issue_template.md) and [pull_request_template.md](https://github.com/cmprescott/ansible-xml/blob/master/.github/pull_request_template.md) have been created. Feel free to correct them. I hope it's not a problem that I skipped the PR and (ab)used the collaborator powers to commit directly.

**Comment by dagwieers** [comment]
@sm4rk0 Looking good. We can close that issue and strike the topic on the action list. Thanks !

**Comment by dagwieers** [comment]
Thanks, I am happy how quick things are moving now. Great to see this.
