### ISSUE TITLE
Get entire xml node

### ISSUE THREAD

**Issue by frsauvage** [cmprescott/ansible-xml#130]
Hi,
I may miss something obvious.
I need all a node inside a hierarchy to register items.

I have a file:
`
<TS>
  <TS_LIST>
    <TS_ITEM>
      <ID>1</ID>
      <NAME>A NAME</NAME>
      <VERSION>A VERSION</VERSION>
    </TS_ITEM>
    <TS_ITEM>
      <ID>2</ID>
      <NAME>ANOTHER NAME</NAME>
      <VERSION>ANOTEHER VERSION</VERSION>
    </TS_ITEM>
  </TS_LIST>
</TS>
`

In my ansible file, I tried:

`
  tasks:
  - name: Read TS xml file
    **xml**:
      path: '/tmp/TS.xml'
      xpath: '/TS/TS_LIST/TS_ITEM'
      input_type : 'xml'
      print_match : yes
    delegate_to: 127.0.0.1
    run_once: true
    register: ts

  - name: "loop through items"
    debug:
      msg: "ts : {{ item.NAME }} and {{ item.VERSION }}"
    delegate_to: 127.0.0.1
    run_once: true
    with_items: {{ ts.matches }}
`
I need to iterate through items from the xml file : Where am I wrong ?
Best Regards,
Francine

**Comment by sm4rk0** [comment]
Hi,

Thank you for your effort to improve this module!

The xml module is upstream now and ships with Ansible since v2.4 (September 2017):
https://github.com/ansible/ansible/blob/devel/docs/docsite/rst/roadmap/ROADMAP_2_4.rst

The feature you need is not implemented (yet?).

If you would like to create a feature request, you should use:
https://github.com/ansible/ansible/issues/new/choose

Cheers,
Marko
