### ISSUE TITLE
add_children before other element

### ISSUE THREAD

**Issue by mathieurousseau** [cmprescott/ansible-xml#131]
`<root>
 <b></b>
 <c></c>
</root>
`
I want to add a children <a> before <b>

**Comment by sm4rk0** [comment]
Thank you for your effort to improve this module!

The xml module is upstream now and ships with Ansible since v2.4 (September 2017):
https://github.com/ansible/ansible/blob/devel/docs/docsite/rst/roadmap/ROADMAP_2_4.rst

The feature you're talking about is added in v2.8 (not yet released).
If you want to try it before v2.8 is released, you can try running ansible from source:
https://docs.ansible.com/ansible/latest/installation_guide/intro_installation.html#running-from-source
The xml module documentation is here:
https://docs.ansible.com/ansible/devel/modules/xml_module.html 

If the issue still exists, please search for it upstream:
https://github.com/ansible/ansible/issues
and report it there if it's not already reported.

**Comment by mathieurousseau** [comment]
Thanks a lot! 
I expect ansible 2.8 to take a long time to reach our internal infra though :-(

**Comment by mathieurousseau** [comment]
I am trying to work around that doing:
- getting /root/* and storing into children_var
- removing /root/*
- adding a to /root
- adding back children_var to /root

unfortunately I was not able to make it work.
- with content: text, I only get the text (not the subelements)
- with content: attribute, I get attribute representation but then add_children does not access that as a parameter

**Comment by dagwieers** [comment]
@mathieurousseau You can always put an improved version in your *./library/* directory until your fixes ship in a release that you *can* use. Also the version in this repository did not receive any of the improvements/fixes that the version in Ansible does have.

Also, Ansible v2.8 is set in stone now, so any new functionality will only ship with Ansible v2.9.

**Comment by sm4rk0** [comment]
@mathieurousseau the workaround not working is related to #130 
But I suggest using new module features/parameters `insertbefore` and `insertafter`.
As @dagwieers said, if Ansible upgrade is not possible you can copy xml.py from v2.8 to your local `library` dir. Note that the module would probably have to be modified because it comes from a newer Ansible version and there could be some changes in [module_utils](https://github.com/ansible/ansible/tree/devel/lib/ansible/module_utils).

**Comment by mathieurousseau** [comment]
Thanks all for the feedback.

I as foresaw 2.8 is not in the short term around here.

I made it work but I had to use external script to extract the elements, then adding what I wanted to then add it back again. works but ugly, waiting for 2.8 to hit us.

BTW do you know if it is possible to add/modify values of attributes more than one at a time?
